### ISSUE TITLE
Fix scrolling behaviour 

### ISSUE THREAD

**Issue by rmp135** [codeweavers/Consign#10]
Currently it isn't possible to scroll down the page. The main pane should be scrollable and the tab bar should remain at the top of the screen.

**Comment by codeweavers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Scrolling](https://trello.com/c/iQyMLfXp/30-fix-scrolling)

**Comment by rmp135** [comment]
Fixed during the redesign.
